server.servlet.context-path: /api
server.port: 8086
spring:
  data:
    mongodb:
      host: 192.168.99.100
      port: 27017
      database: testdb
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 192.168.99.100:9300
  elasticsearch:
    rest:
      uris: http://192.168.99.100:9200

app:
  prop1: prop1
  prop2: prop2
